### ISSUE TITLE
How do I generate video summary

### ISSUE THREAD

**Issue by chibexme** [TIBHannover/UnsupervisedVideoSummarization#3]
Great job, 

I finished setting up the project, trained my model and performed test. 

My question now is how can I generate video summary (which file should I execute and what parameters should pass)?

**Comment by hussainkanafani** [comment]
Hello @chibexme,
thanks!
you may use the src/evaluation/evaluate.py script with the configs from either config_summe.yaml or config_tvsum.yaml
