### ISSUE TITLE
Problem running TVSum for the late-fusion version

### ISSUE THREAD

**Issue by mpalaourg** [TIBHannover/UnsupervisedVideoSummarization#5]
Hello and thank you for making your code open-source,

I am trying to run your code and especially the version with the late-fusion. For `SumMe` is all good and running w/o any problem. However, for the `TVSum` dataset, I get an error because of `get_difference_attention` won't return a proper value for the `motion_attention` attribute. After some digging I found that this folder doesn't contain 4 pickle files (like the others), but 3 and the missing one is the `tvsum_places365_attention.pickle`.

Can you upload this file? Or can I use the one of the other folders?

Thanks in advance

**Comment by hussainkanafani** [comment]
Hello @mpalaourg,
actually, you can use the one in other folders.
